import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { CtaSection } from "@/components/cta-section";
import { PageHero } from "@/components/page-hero";

export const metadata: Metadata = { title: "Leistungen", description: "Photovoltaik, Batteriespeicher, Wallboxen und Energiemanagement als abgestimmtes System." };
const items = [
  { id:"photovoltaik", title:"Photovoltaikanlagen", eyebrow:"Strom vom eigenen Dach", copy:"Wir planen die Anlage entlang Ihrer Dachgeometrie, Ihres Verbrauchs und Ihrer gestalterischen Ansprüche. Das Ergebnis ist technisch belastbar und sauber in die Architektur integriert.", benefits:["Dachgenaue Belegungsplanung", "Nachvollziehbare Ertragsprognose", "Hochwertige Module und Wechselrichter", "Anmeldung und Inbetriebnahme koordiniert"], image:"/images/hero-home.png", href:"/leistungen/photovoltaik" },
  { id:"speicher", title:"Batteriespeicher", eyebrow:"Solarstrom nach Sonnenuntergang", copy:"Ein passend dimensionierter Speicher verschiebt Energie in die Stunden, in denen Ihr Haushalt sie wirklich benötigt. Wir vermeiden Überdimensionierung und schaffen Raum für spätere Anforderungen.", benefits:["Am Lastprofil orientierte Kapazität", "Bestehende Anlagen nachrüstbar", "Transparente Betriebsdaten", "Optionale Notstromkonzepte"], image:"/images/energy-system.png" },
  { id:"wallbox", title:"Wallboxen", eyebrow:"Mobilität sinnvoll integrieren", copy:"Die Wallbox wird Teil des Energiesystems – mit Überschussladen, sinnvoller Ladeleistung und Blick auf den Hausanschluss. So wird eigenes Laden planbar und komfortabel.", benefits:["PV-Überschussladen", "Dynamisches Lastmanagement", "Vorbereitung für weitere Ladepunkte", "Saubere Installation und Einweisung"], image:"/images/solar-installation.png" },
  { id:"energiemanagement", title:"Energiemanagement", eyebrow:"Verbrauch intelligent steuern", copy:"Ein Energiemanagement verbindet Erzeugung, Speicher, Wärmepumpe und Mobilität. Es schafft Transparenz und verschiebt flexible Verbräuche in ertragreiche Stunden.", benefits:["Zentrale Verbrauchsübersicht", "Automatisierte Energieflüsse", "Wärmepumpe und Wallbox einbindbar", "Erweiterbar für künftige Technik"], image:"/images/energy-system.png" },
];
export default function ServicesPage() { return <main id="inhalt"><PageHero eyebrow="Leistungen" title="Energielösungen, die zusammenspielen." copy="Wir planen keine isolierten Produkte. Wir entwickeln ein System, das zu Ihrem Dach, Ihrem Verbrauch und Ihren nächsten Jahren passt." label="Planung · Montage · Service" /><div className="shell">{items.map((item,index) => <section className={`editorial-section ${index % 2 ? "reverse" : ""}`} id={item.id} key={item.id}><div className="image-frame editorial-image"><Image src={item.image} alt={`${item.title} von VOLTWERK`} fill sizes="(max-width: 640px) 100vw, 50vw" /></div><div className="editorial-copy"><p className="eyebrow">{item.eyebrow}</p><h2 className="headline">{item.title}</h2><p className="lead">{item.copy}</p><ul className="benefit-list">{item.benefits.map((benefit) => <li key={benefit}><Check aria-hidden="true" /> {benefit}</li>)}</ul><div className="button-row"><Link className="text-link" href={item.href ?? "/kontakt"}>{item.href ? "Photovoltaik im Detail" : "Beratung anfragen"} <ArrowRight aria-hidden="true" /></Link></div></div></section>)}</div><CtaSection /></main>; }
