import { ResponsiveImage } from "@/components/responsive-image";
import Link from "next/link";
import { ArrowRight, BatteryCharging, Cable, Gauge, SolarPanel } from "lucide-react";
import { CtaSection } from "@/components/cta-section";
import { FaqAccordion } from "@/components/faq-accordion";
import { ProjectCard } from "@/components/project-card";
import { SectionHeading } from "@/components/section-heading";
import { SolarCalculator } from "@/components/solar-calculator";
import { faqs, projects, services } from "@/lib/content";
import { createPageMetadata } from "@/lib/metadata";

export const metadata = createPageMetadata({ title: "Eigene Energie für Ihr Zuhause", description: "VOLTWERK plant und realisiert Photovoltaik, Speicher, Wallboxen und intelligentes Energiemanagement in Nordrhein-Westfalen.", path: "/" });
const icons = [SolarPanel, BatteryCharging, Cable, Gauge];

export default function Home() {
  return <main id="inhalt">
    <section className="hero" aria-labelledby="hero-title"><ResponsiveImage className="hero-image" src="/images/hero-solar-home.webp" alt="Modernes Einfamilienhaus mit Photovoltaikanlage auf dem Dach" priority sizes="100vw" /><div className="shell hero-inner"><div className="hero-copy"><p className="eyebrow">Photovoltaik & Energielösungen aus NRW</p><h1 className="display" id="hero-title">Ihre Energie.<br />Ihr Zuhause.<br />Ihre Zukunft.</h1><p className="lead">Photovoltaik, Speicher und intelligente Energielösungen aus einer Hand – individuell geplant und professionell umgesetzt.</p><div className="button-row"><Link className="button button-primary" href="/kontakt">Kostenlose Beratung anfragen <ArrowRight aria-hidden="true" /></Link><Link className="button button-ghost" href="/projekte">Projekte ansehen</Link></div></div></div><div className="hero-note">Planung, Montage und Service aus einer Hand</div></section>
    <section className="stat-strip" aria-label="VOLTWERK in Zahlen"><div className="shell stats">{[["250+", "realisierte Anlagen"], ["12 Jahre", "Erfahrung"], ["4,9/5", "Kundenzufriedenheit"], ["100 %", "individuelle Planung"]].map(([value, label]) => <div className="stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
    <section className="section"><div className="shell intro-grid"><SectionHeading eyebrow="Unsere Leistungen" title="Energie, die zu Ihrem Zuhause passt." copy="Keine Bausteine von der Stange. Wir verbinden Technik, Verbrauch und Architektur zu einem System, das heute funktioniert und morgen erweiterbar bleibt." /><div className="service-list">{services.map((service, index) => { const Icon = icons[index]; return <article className="service-row" key={service.title}><Icon aria-hidden="true" /><div><h3>{service.title}</h3><p>{service.description}</p></div><Link className="arrow-link" href={service.href} aria-label={`${service.title} ansehen`}><ArrowRight aria-hidden="true" /></Link></article>; })}</div></div></section>
    <section className="section-sm section-white"><div className="shell why-layout"><div className="image-frame why-image"><ResponsiveImage src="/images/solar-installation.webp" alt="Fachgerechte Montage von Solarmodulen auf einem Hausdach" sizes="(max-width: 900px) 100vw, 58vw" /></div><div className="why-copy"><p className="eyebrow">Warum VOLTWERK</p><h2 className="headline">Technik ist nur dann gut, wenn alles zusammenpasst.</h2><div className="why-points">{[["01", "Persönliche Planung", "Ein fester Ansprechpartner begleitet Ihr Projekt."], ["02", "Hochwertige Komponenten", "Ausgewählt nach Leistung, Verfügbarkeit und Service."], ["03", "Montage aus einer Hand", "Eigene Planung und koordinierte Fachgewerke."], ["04", "Regional erreichbar", "Kurze Wege in Nordrhein-Westfalen."]].map(([n, title, copy]) => <div className="why-point" key={title}><strong>{n}</strong><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div></div></div></section>
    <section className="section"><div className="shell"><div className="split"><SectionHeading eyebrow="Ausgewählte Projekte" title="Gute Planung zeigt sich im Detail." /><div><p className="lead">Dachform, Lastprofil und Zukunftspläne unterscheiden sich. Deshalb gleicht auch keine unserer Lösungen der anderen.</p><div className="button-row"><Link className="text-link" href="/projekte">Alle Projekte ansehen <ArrowRight aria-hidden="true" /></Link></div></div></div><div className="project-grid all-projects">{projects.slice(0,4).map((project) => <ProjectCard key={project.location} project={project} />)}</div></div></section>
    <section className="section section-dark"><div className="shell"><SectionHeading eyebrow="So arbeiten wir" title="Vier Schritte. Ein verlässlicher Ablauf." copy="Von der ersten Idee bis zum selbst erzeugten Strom behalten Sie einen Ansprechpartner und klare nächste Schritte." /><div className="timeline">{[["01", "Beratung", "Ziele, Verbrauch und Rahmenbedingungen gemeinsam klären."], ["02", "Planung", "Dach, Technik und Wirtschaftlichkeit präzise auslegen."], ["03", "Installation", "Montage, Elektroarbeiten und Anmeldung koordinieren."], ["04", "Energie nutzen", "System erklären, überwachen und bei Fragen erreichbar bleiben."]].map(([num,title,copy]) => <div className="timeline-step" key={num}><span className="num">{num}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>
    <section className="section"><div className="shell"><SolarCalculator /></div></section>
    <section className="section-sm section-white"><div className="shell"><SectionHeading eyebrow="Stimmen aus der Region" title="Klar beraten. Sauber umgesetzt." /><div className="quotes">{[["„Vom ersten Termin bis zur Einweisung wussten wir immer, was als Nächstes passiert. Besonders geholfen hat uns der ehrliche Vergleich verschiedener Speichergrößen.“", "Anna und Marc W. · Gütersloh · fiktive Referenz"], ["„Die Anlage fügt sich viel ruhiger ins Dach ein, als wir erwartet hatten. Die Baustelle war gut organisiert und am Ende sauber.“", "Sabine K. · Bielefeld · fiktive Referenz"], ["„Photovoltaik und Wallbox arbeiten so zusammen, wie es für unseren Alltag sinnvoll ist. Keine unnötige Technik, sondern eine nachvollziehbare Lösung.“", "Familie L. · Paderborn · fiktive Referenz"], ["„Auch nach der Inbetriebnahme wurden unsere Fragen schnell und verständlich beantwortet. Wir fühlen uns mit der Anlage im Alltag gut begleitet.“", "Miriam und Jens R. · Münster · fiktive Referenz"]].map(([quote,person]) => <figure className="quote" key={person}><blockquote>{quote}</blockquote><figcaption>{person}</figcaption></figure>)}</div></div></section>
    <section className="section"><div className="shell faq-wrap"><SectionHeading eyebrow="Häufige Fragen" title="Was Sie vor dem Start wissen sollten." copy="Eine gute Entscheidung beginnt mit verständlichen Antworten." /><FaqAccordion items={faqs} /></div></section>
    <CtaSection />
  </main>;
}
